name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e
            cd /home/barberia_vps/Barberia-Reservas-Simple-Project || { echo "❌ Carpeta no encontrada"; exit 1; }
            echo "📦 Actualizando código..."
            git pull origin main
            echo "🧱 Reconstruyendo contenedores..."
            docker compose down
            docker compose pull
            docker compose build
            docker compose up -d
            docker system prune -f
            echo "✅ Deploy completado con éxito"
            docker ps
